<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23" started-at="2015-03-16T03:30:25Z" finished-at="2015-03-16T03:30:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23" started-at="2015-03-16T03:30:25Z" finished-at="2015-03-16T03:30:25Z">
      <class name="Jam.AllYourbaseTest">
        <test-method status="PASS" signature="getBaseValue1()[pri:0, instance:Jam.AllYourbaseTest@447ec736]" name="getBaseValue1" duration-ms="10" started-at="2015-03-15T20:30:25Z" finished-at="2015-03-15T20:30:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getBaseValue1 -->
        <test-method status="FAIL" signature="getDec()[pri:0, instance:Jam.AllYourbaseTest@447ec736]" name="getDec" duration-ms="1" started-at="2015-03-15T20:30:25Z" finished-at="2015-03-15T20:30:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [201] but found [29480883458974409]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [201] but found [29480883458974409]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Jam.AllYourbaseTest.getDec(AllYourbaseTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1203)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.run(TestNG.java:1036)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getDec -->
        <test-method status="PASS" signature="main()[pri:0, instance:Jam.AllYourbaseTest@447ec736]" name="main" duration-ms="1" started-at="2015-03-15T20:30:25Z" finished-at="2015-03-15T20:30:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- main -->
      </class> <!-- Jam.AllYourbaseTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
